/**
 * Initial catalogue. Written to `data/products.json` the first time the store
 * is read, after which the JSON file is authoritative and this is never
 * consulted again — admin edits are never overwritten by the seed.
 *
 * GENERATED by scripts/build-catalogue.mjs. Edit the spec, not this file.
 */
import { Product } from '@/types';

export const SEED_PRODUCTS: Product[] = [
  {
    "id": "1",
    "slug": "jersey-hijab",
    "name": "Jersey Hijab",
    "subtitle": "The everyday one",
    "description": "Soft, stretchable and easy to style — our everyday jersey hijab holds its shape all day without a single pin. The cotton-blend knit has a matte finish and just enough weight to drape cleanly around the face.",
    "price": 22,
    "category": "Hijabs",
    "images": [
      "/products/jersey-hijab-burgundy-2a9b49.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-1-burgundy",
        "colorName": "Burgundy",
        "hex": "#6e1f2e",
        "sku": "GG-JERHIJ-BUR",
        "stock": 10,
        "images": [
          "/products/jersey-hijab-burgundy-2a9b49.webp"
        ]
      },
      {
        "id": "v-1-mauve",
        "colorName": "Mauve",
        "hex": "#8c6272",
        "sku": "GG-JERHIJ-MAU",
        "stock": 10,
        "images": [
          "/products/jersey-hijab-mauve-5ef1ee.webp"
        ]
      },
      {
        "id": "v-1-camel",
        "colorName": "Camel",
        "hex": "#c79b6c",
        "sku": "GG-JERHIJ-CAM",
        "stock": 10,
        "images": [
          "/products/jersey-hijab-camel-6b06c3.webp",
          "/products/jersey-hijab-camel-2-84f20b.webp"
        ]
      },
      {
        "id": "v-1-teal",
        "colorName": "Teal",
        "hex": "#0e6b70",
        "sku": "GG-JERHIJ-TEA",
        "stock": 10,
        "images": [
          "/products/jersey-hijab-teal-a9edc3.webp"
        ]
      },
      {
        "id": "v-1-dusty-rose",
        "colorName": "Dusty Rose",
        "hex": "#d08a96",
        "sku": "GG-JERHIJ-DUSROS",
        "stock": 10,
        "images": [
          "/products/jersey-hijab-dusty-rose-2ad29c.webp"
        ]
      },
      {
        "id": "v-1-rose-mauve",
        "colorName": "Rose Mauve",
        "hex": "#c17a8a",
        "sku": "GG-JERHIJ-ROSMAU",
        "stock": 10,
        "images": [
          "/products/jersey-hijab-rose-mauve-5a8169.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 75 cm",
      "Cotton-blend jersey knit, four-way stretch",
      "Matte finish, medium opacity — no underscarf needed for most",
      "Raw-cut edges, so it will not fray or roll",
      "Machine wash cold on a gentle cycle. Cool iron if needed."
    ],
    "tags": [
      "top-selling",
      "trending"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "2",
    "slug": "ribbed-jersey-hijab",
    "name": "Ribbed Jersey Hijab",
    "subtitle": "Texture and grip",
    "description": "The same easy jersey comfort with a fine rib running through it. The texture gives the fabric grip, so folds stay exactly where you set them — the practical choice for a long day.",
    "price": 24,
    "category": "Hijabs",
    "images": [
      "/products/ribbed-jersey-hijab-hero-f8ad4b.webp",
      "/products/ribbed-jersey-hijab-hero-194ac4.webp",
      "/products/ribbed-jersey-hijab-hero-5bcb10.webp",
      "/products/ribbed-jersey-hijab-dove-grey-21e739.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-2-dove-grey",
        "colorName": "Dove Grey",
        "hex": "#b7bbbc",
        "sku": "GG-RIBJERHIJ-DOVGRE",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-dove-grey-21e739.webp"
        ]
      },
      {
        "id": "v-2-burgundy",
        "colorName": "Burgundy",
        "hex": "#551a2a",
        "sku": "GG-RIBJERHIJ-BUR",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-burgundy-e2ddd5.webp"
        ]
      },
      {
        "id": "v-2-sand",
        "colorName": "Sand",
        "hex": "#c7b791",
        "sku": "GG-RIBJERHIJ-SAN",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-sand-96b769.webp"
        ]
      },
      {
        "id": "v-2-sage-green",
        "colorName": "Sage Green",
        "hex": "#a7ac8a",
        "sku": "GG-RIBJERHIJ-SAGGRE",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-sage-green-8401d6.webp"
        ]
      },
      {
        "id": "v-2-navy-blue",
        "colorName": "Navy Blue",
        "hex": "#1b2340",
        "sku": "GG-RIBJERHIJ-NAVBLU",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-navy-blue-58cb8e.webp"
        ]
      },
      {
        "id": "v-2-taupe",
        "colorName": "Taupe",
        "hex": "#a5978a",
        "sku": "GG-RIBJERHIJ-TAU",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-taupe-3e8fed.webp"
        ]
      },
      {
        "id": "v-2-midnight-black",
        "colorName": "Midnight Black",
        "hex": "#1a1a1a",
        "sku": "GG-RIBJERHIJ-MIDBLA",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-midnight-black-d8f3b2.webp"
        ]
      },
      {
        "id": "v-2-rose-mauve",
        "colorName": "Rose Mauve",
        "hex": "#a06678",
        "sku": "GG-RIBJERHIJ-ROSMAU",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-rose-mauve-c48643.webp"
        ]
      },
      {
        "id": "v-2-oatmeal",
        "colorName": "Oatmeal",
        "hex": "#e2dbc9",
        "sku": "GG-RIBJERHIJ-OAT",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-hijab-oatmeal-ed5653.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 75 cm",
      "Ribbed cotton-blend jersey, four-way stretch",
      "Textured surface grips itself and holds a fold",
      "Slightly heavier than plain jersey, fully opaque",
      "Machine wash cold on a gentle cycle. Cool iron if needed."
    ],
    "tags": [
      "new-arrivals",
      "trending",
      "top-selling"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "3",
    "slug": "georgette-hijab",
    "name": "Georgette Hijab",
    "subtitle": "Light and fluid",
    "description": "A featherlight crinkle georgette that moves with you. It falls in soft folds rather than sitting flat, which makes it the easy pick for warm weather and for anyone who prefers a lighter drape.",
    "price": 25,
    "category": "Hijabs",
    "images": [
      "/products/georgette-hijab-ivory-e85550.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-3-ivory",
        "colorName": "Ivory",
        "hex": "#f4f2ec",
        "sku": "GG-GEOHIJ-IVO",
        "stock": 10,
        "images": [
          "/products/georgette-hijab-ivory-e85550.webp"
        ]
      },
      {
        "id": "v-3-navy-blue",
        "colorName": "Navy Blue",
        "hex": "#1b2140",
        "sku": "GG-GEOHIJ-NAVBLU",
        "stock": 10,
        "images": [
          "/products/georgette-hijab-navy-blue-e72c79.webp"
        ]
      },
      {
        "id": "v-3-taupe",
        "colorName": "Taupe",
        "hex": "#a89686",
        "sku": "GG-GEOHIJ-TAU",
        "stock": 10,
        "images": [
          "/products/georgette-hijab-taupe-1a10ff.webp"
        ]
      },
      {
        "id": "v-3-olive-green",
        "colorName": "Olive Green",
        "hex": "#5b6a3c",
        "sku": "GG-GEOHIJ-OLIGRE",
        "stock": 10,
        "images": [
          "/products/georgette-hijab-olive-green-39539f.webp"
        ]
      },
      {
        "id": "v-3-burgundy",
        "colorName": "Burgundy",
        "hex": "#7a1f30",
        "sku": "GG-GEOHIJ-BUR",
        "stock": 10,
        "images": [
          "/products/georgette-hijab-burgundy-38abfe.webp"
        ]
      },
      {
        "id": "v-3-dusty-rose",
        "colorName": "Dusty Rose",
        "hex": "#d99aa0",
        "sku": "GG-GEOHIJ-DUSROS",
        "stock": 10,
        "images": [
          "/products/georgette-hijab-dusty-rose-cdb832.webp"
        ]
      },
      {
        "id": "v-3-rose-mauve",
        "colorName": "Rose Mauve",
        "hex": "#a9788a",
        "sku": "GG-GEOHIJ-ROSMAU",
        "stock": 10,
        "images": [
          "/products/georgette-hijab-rose-mauve-6477d4.webp"
        ]
      },
      {
        "id": "v-3-deep-plum",
        "colorName": "Deep Plum",
        "hex": "#5c1f52",
        "sku": "GG-GEOHIJ-DEEPLU",
        "stock": 10,
        "images": [
          "/products/georgette-hijab-deep-plum-a69185.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 75 cm",
      "Crinkle georgette, woven — no stretch",
      "Lightweight and semi-sheer; an underscarf is recommended",
      "Textured crinkle finish that resists creasing",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "4",
    "slug": "silk-scarf",
    "name": "Silk Scarf",
    "subtitle": "For the occasion",
    "description": "A satin-finish scarf with real sheen, printed in classic motifs. Heavier and smoother than our chiffon prints, it holds a knot beautifully and reads as dressed-up without any effort.",
    "price": 45,
    "category": "Scarves",
    "images": [
      "/products/silk-scarf-hero-ec22b1.webp",
      "/products/silk-scarf-navy-medallion-print-6521c9.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-4-navy-medallion-print",
        "colorName": "Navy Medallion Print",
        "hex": "#1e2a52",
        "sku": "GG-SILSCA-NAVMED",
        "stock": 10,
        "images": [
          "/products/silk-scarf-navy-medallion-print-6521c9.webp"
        ]
      },
      {
        "id": "v-4-mustard-houndstooth-patchwork-print",
        "colorName": "Mustard Houndstooth Patchwork Print",
        "hex": "#c9a227",
        "sku": "GG-SILSCA-MUSHOU",
        "stock": 10,
        "images": [
          "/products/silk-scarf-mustard-houndstooth-patchwork-print-b67c64.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Satin-finish woven scarf fabric with a soft lustre",
      "Fluid drape, holds a knot without slipping",
      "Neatly hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "trending",
      "top-selling"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "5",
    "slug": "embroidered-paisley-border-pashmina",
    "name": "Embroidered Paisley Border Pashmina",
    "subtitle": "Embroidered border",
    "description": "A finely woven pashmina-weight shawl with a dense embroidered paisley border running down each long edge. Warm without bulk, and formal enough for an event while still working over a coat.",
    "price": 40,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/embroidered-paisley-border-pashmina-espresso-brown-ba1abd.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-5-espresso-brown",
        "colorName": "Espresso Brown",
        "hex": "#3a2e22",
        "sku": "GG-EMBPAIBOR-ESPBRO",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-espresso-brown-ba1abd.webp",
          "/products/embroidered-paisley-border-pashmina-espresso-brown-2-57777b.webp",
          "/products/embroidered-paisley-border-pashmina-espresso-brown-3-870839.webp"
        ]
      },
      {
        "id": "v-5-ivory",
        "colorName": "Ivory",
        "hex": "#e5ddc8",
        "sku": "GG-EMBPAIBOR-IVO",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-ivory-64dc9d.webp"
        ]
      },
      {
        "id": "v-5-oatmeal-beige",
        "colorName": "Oatmeal Beige",
        "hex": "#c6bca6",
        "sku": "GG-EMBPAIBOR-OATBEI",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-oatmeal-beige-23c11f.webp",
          "/products/embroidered-paisley-border-pashmina-oatmeal-beige-2-25103e.webp"
        ]
      },
      {
        "id": "v-5-olive-green",
        "colorName": "Olive Green",
        "hex": "#5a5230",
        "sku": "GG-EMBPAIBOR-OLIGRE",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-olive-green-c9054b.webp",
          "/products/embroidered-paisley-border-pashmina-olive-green-2-97afd1.webp"
        ]
      },
      {
        "id": "v-5-midnight-black",
        "colorName": "Midnight Black",
        "hex": "#14120f",
        "sku": "GG-EMBPAIBOR-MIDBLA",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-midnight-black-fb089f.webp",
          "/products/embroidered-paisley-border-pashmina-midnight-black-2-1f3fe0.webp",
          "/products/embroidered-paisley-border-pashmina-midnight-black-3-7e41a4.webp",
          "/products/embroidered-paisley-border-pashmina-midnight-black-4-662e7e.webp"
        ]
      },
      {
        "id": "v-5-wine-burgundy",
        "colorName": "Wine Burgundy",
        "hex": "#5a1b2e",
        "sku": "GG-EMBPAIBOR-WINBUR",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-wine-burgundy-f7f0a1.webp",
          "/products/embroidered-paisley-border-pashmina-wine-burgundy-2-9cd621.webp"
        ]
      },
      {
        "id": "v-5-navy-blue",
        "colorName": "Navy Blue",
        "hex": "#1e2a47",
        "sku": "GG-EMBPAIBOR-NAVBLU",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-navy-blue-e30ee0.webp"
        ]
      },
      {
        "id": "v-5-deep-plum",
        "colorName": "Deep Plum",
        "hex": "#48174a",
        "sku": "GG-EMBPAIBOR-DEEPLU",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-deep-plum-62aef8.webp"
        ]
      },
      {
        "id": "v-5-forest-green",
        "colorName": "Forest Green",
        "hex": "#1b3428",
        "sku": "GG-EMBPAIBOR-FORGRE",
        "stock": 10,
        "images": [
          "/products/embroidered-paisley-border-pashmina-forest-green-f9cffb.webp",
          "/products/embroidered-paisley-border-pashmina-forest-green-2-f9cffb.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Fine woven wool-blend shawl fabric, soft matte finish",
      "Embroidered paisley border on both long edges",
      "Hand-knotted fringe",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [
      "top-selling",
      "trending"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "6",
    "slug": "striped-paisley-pashmina",
    "name": "Striped Paisley Pashmina",
    "subtitle": "Woven stripe",
    "description": "Tonal stripes woven through a soft pashmina-weight ground, with paisley detailing at the ends. Quieter than the embroidered border, and easier to wear with a patterned outfit.",
    "price": 40,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/striped-paisley-pashmina-stone-beige-655ea3.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-6-stone-beige",
        "colorName": "Stone Beige",
        "hex": "#b7ad97",
        "sku": "GG-STRPAIPAS-STOBEI",
        "stock": 10,
        "images": [
          "/products/striped-paisley-pashmina-stone-beige-655ea3.webp"
        ]
      },
      {
        "id": "v-6-burgundy",
        "colorName": "Burgundy",
        "hex": "#5a1220",
        "sku": "GG-STRPAIPAS-BUR",
        "stock": 10,
        "images": [
          "/products/striped-paisley-pashmina-burgundy-950e51.webp"
        ]
      },
      {
        "id": "v-6-black",
        "colorName": "Black",
        "hex": "#171410",
        "sku": "GG-STRPAIPAS-BLA",
        "stock": 10,
        "images": [
          "/products/striped-paisley-pashmina-black-002ed4.webp",
          "/products/striped-paisley-pashmina-black-2-d75620.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Fine woven wool-blend shawl fabric",
      "Tonal woven stripe with paisley end panels",
      "Hand-knotted fringe",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "7",
    "slug": "medallion-embroidered-pashmina",
    "name": "Medallion Embroidered Pashmina",
    "subtitle": "Centre medallion",
    "description": "A statement shawl with a large embroidered medallion worked across the body and a decorated border. This is the one for a wedding or an evening event.",
    "price": 45,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/medallion-embroidered-pashmina-hero-7212aa.webp",
      "/products/medallion-embroidered-pashmina-emerald-green-916623.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-7-emerald-green",
        "colorName": "Emerald Green",
        "hex": "#163a2e",
        "sku": "GG-MEDEMBPAS-EMEGRE",
        "stock": 10,
        "images": [
          "/products/medallion-embroidered-pashmina-emerald-green-916623.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Fine woven wool-blend shawl fabric",
      "Large embroidered medallion motif with a worked border",
      "Hand-knotted fringe",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [
      "top-selling"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "8",
    "slug": "ornate-corner-pashmina",
    "name": "Ornate Corner Pashmina",
    "subtitle": "Corner embroidery",
    "description": "Embroidery concentrated at the corners, so the detail sits where it shows — over the shoulder and at the fall. Plain through the body, which keeps it from competing with what you are wearing.",
    "price": 45,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/ornate-corner-pashmina-dark-teal-f015ce.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-8-dark-teal",
        "colorName": "Dark Teal",
        "hex": "#1b3b39",
        "sku": "GG-ORNCORPAS-DARTEA",
        "stock": 10,
        "images": [
          "/products/ornate-corner-pashmina-dark-teal-f015ce.webp"
        ]
      },
      {
        "id": "v-8-crimson-red",
        "colorName": "Crimson Red",
        "hex": "#8a1621",
        "sku": "GG-ORNCORPAS-CRIRED",
        "stock": 10,
        "images": [
          "/products/ornate-corner-pashmina-crimson-red-f372d0.webp"
        ]
      },
      {
        "id": "v-8-indigo-navy",
        "colorName": "Indigo Navy",
        "hex": "#1b2340",
        "sku": "GG-ORNCORPAS-INDNAV",
        "stock": 10,
        "images": [
          "/products/ornate-corner-pashmina-indigo-navy-0e8aa8.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Fine woven wool-blend shawl fabric",
      "Ornate embroidered corner motifs, plain ground",
      "Hand-knotted fringe",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [
      "trending"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "9",
    "slug": "classic-twill-stole",
    "name": "Classic Twill Stole",
    "subtitle": "Plain and warm",
    "description": "A plain twill-woven stole with a tight, flat weave and a deep hand-knotted fringe. No pattern, no shine — just a warm, well-made winter layer in a colour that will go with everything.",
    "price": 59,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/classic-twill-stole-mocha-101c59.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-9-mocha",
        "colorName": "Mocha",
        "hex": "#8c8175",
        "sku": "GG-CLATWISTO-MOC",
        "stock": 10,
        "images": [
          "/products/classic-twill-stole-mocha-101c59.webp"
        ]
      },
      {
        "id": "v-9-dusty-lavender",
        "colorName": "Dusty Lavender",
        "hex": "#7a7290",
        "sku": "GG-CLATWISTO-DUSLAV",
        "stock": 10,
        "images": [
          "/products/classic-twill-stole-dusty-lavender-174486.webp"
        ]
      },
      {
        "id": "v-9-burgundy",
        "colorName": "Burgundy",
        "hex": "#5a1f2b",
        "sku": "GG-CLATWISTO-BUR",
        "stock": 10,
        "images": [
          "/products/classic-twill-stole-burgundy-3549b8.webp"
        ]
      },
      {
        "id": "v-9-navy",
        "colorName": "Navy",
        "hex": "#202a4a",
        "sku": "GG-CLATWISTO-NAV",
        "stock": 10,
        "images": [
          "/products/classic-twill-stole-navy-957fa5.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Tight twill weave with a soft matte surface",
      "Approx. 10 cm hand-knotted fringe",
      "Substantial winter weight",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "10",
    "slug": "heathered-boucle-stole",
    "name": "Heathered Boucle Stole",
    "subtitle": "Brushed and soft",
    "description": "A brushed bouclé stole with a flecked, heathered surface and a noticeably soft hand. Lighter and fuzzier than the twill, and the melange colour hides everyday wear well.",
    "price": 55,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/heathered-boucle-stole-oatmeal-heather-6e60e9.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-10-oatmeal-heather",
        "colorName": "Oatmeal Heather",
        "hex": "#b7a996",
        "sku": "GG-HEABOUSTO-OATHEA",
        "stock": 10,
        "images": [
          "/products/heathered-boucle-stole-oatmeal-heather-6e60e9.webp",
          "/products/heathered-boucle-stole-oatmeal-heather-2-7ace1e.webp"
        ]
      },
      {
        "id": "v-10-lilac-heather",
        "colorName": "Lilac Heather",
        "hex": "#9089a3",
        "sku": "GG-HEABOUSTO-LILHEA",
        "stock": 10,
        "images": [
          "/products/heathered-boucle-stole-lilac-heather-0d7847.webp",
          "/products/heathered-boucle-stole-lilac-heather-2-2b0808.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Brushed bouclé knit with a heathered melange surface",
      "Soft, lofty handle",
      "Hand-knotted fringe",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "11",
    "slug": "rose-jacquard-stole",
    "name": "Rose Jacquard Stole",
    "subtitle": "Tonal rose motif",
    "description": "A rose motif woven tone-on-tone into the ground, so the pattern catches the light rather than shouting. Smooth-faced, warm, and dressier than a plain stole.",
    "price": 62,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/rose-jacquard-stole-camel-eb1d80.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-11-camel",
        "colorName": "Camel",
        "hex": "#c6a576",
        "sku": "GG-ROSJACSTO-CAM",
        "stock": 10,
        "images": [
          "/products/rose-jacquard-stole-camel-eb1d80.webp"
        ]
      },
      {
        "id": "v-11-grey",
        "colorName": "Grey",
        "hex": "#b4afa9",
        "sku": "GG-ROSJACSTO-GRE",
        "stock": 10,
        "images": [
          "/products/rose-jacquard-stole-grey-1bf75a.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Tonal jacquard weave, rose motif",
      "Smooth face with a subtle raised pattern",
      "Hand-knotted fringe",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [
      "trending"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "12",
    "slug": "embossed-paisley-stole",
    "name": "Embossed Paisley Stole",
    "subtitle": "Raised paisley",
    "description": "Paisley embossed into a smooth ground — the pattern is felt as much as seen. A quiet, tactile stole that works as well over a coat as it does indoors.",
    "price": 62,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/embossed-paisley-stole-magenta-0a3602.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-12-magenta",
        "colorName": "Magenta",
        "hex": "#96206b",
        "sku": "GG-EMBPAISTO-MAG",
        "stock": 10,
        "images": [
          "/products/embossed-paisley-stole-magenta-0a3602.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Smooth ground with a raised embossed paisley pattern",
      "Hand-knotted fringe",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "13",
    "slug": "camel-leopard-paisley-print-stole",
    "name": "Camel Leopard Paisley Print Stole",
    "subtitle": "Printed animal paisley",
    "description": "Leopard and paisley printed together over a warm camel ground. Bold, but the tonal palette keeps it wearable with a plain coat.",
    "price": 62,
    "category": "Pashminas & Stoles",
    "images": [
      "/products/camel-leopard-paisley-print-stole-camel-leopard-paisley-849f5a.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-13-camel-leopard-paisley",
        "colorName": "Camel Leopard Paisley",
        "hex": "#a97c46",
        "sku": "GG-CAMLEOPAI-CAMLEO",
        "stock": 10,
        "images": [
          "/products/camel-leopard-paisley-print-stole-camel-leopard-paisley-849f5a.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 200 × 70 cm plus fringe",
      "Printed on a smooth woven ground",
      "Hand-knotted fringe",
      "Dry clean recommended. Do not tumble dry."
    ],
    "tags": [
      "trending"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "14",
    "slug": "ribbed-jersey-tube-cap",
    "name": "Ribbed Jersey Tube Cap",
    "subtitle": "Grip that holds",
    "description": "A ribbed jersey tube cap that sits close to the head and gives your hijab something to grip. Pull it on, set your hairline, and nothing shifts for the rest of the day.",
    "price": 12,
    "category": "Underscarves",
    "images": [
      "/products/ribbed-jersey-tube-cap-black-065225.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-14-black",
        "colorName": "Black",
        "hex": "#1b1b1b",
        "sku": "GG-RIBJERTUB-BLA",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-black-065225.webp"
        ]
      },
      {
        "id": "v-14-mustard",
        "colorName": "Mustard",
        "hex": "#a97022",
        "sku": "GG-RIBJERTUB-MUS",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-mustard-b2d8b5.webp"
        ]
      },
      {
        "id": "v-14-camel",
        "colorName": "Camel",
        "hex": "#c9a873",
        "sku": "GG-RIBJERTUB-CAM",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-camel-c9254a.webp"
        ]
      },
      {
        "id": "v-14-dusty-rose",
        "colorName": "Dusty Rose",
        "hex": "#d6aca3",
        "sku": "GG-RIBJERTUB-DUSROS",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-dusty-rose-e1d043.webp"
        ]
      },
      {
        "id": "v-14-caramel",
        "colorName": "Caramel",
        "hex": "#b87a34",
        "sku": "GG-RIBJERTUB-CAR",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-caramel-e9b2d1.webp"
        ]
      },
      {
        "id": "v-14-navy",
        "colorName": "Navy",
        "hex": "#1c2740",
        "sku": "GG-RIBJERTUB-NAV",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-navy-7027ff.webp"
        ]
      },
      {
        "id": "v-14-burgundy",
        "colorName": "Burgundy",
        "hex": "#5e1a28",
        "sku": "GG-RIBJERTUB-BUR",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-burgundy-a13901.webp"
        ]
      },
      {
        "id": "v-14-taupe",
        "colorName": "Taupe",
        "hex": "#c6ac95",
        "sku": "GG-RIBJERTUB-TAU",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-taupe-5c7471.webp"
        ]
      },
      {
        "id": "v-14-mauve",
        "colorName": "Mauve",
        "hex": "#8c6672",
        "sku": "GG-RIBJERTUB-MAU",
        "stock": 10,
        "images": [
          "/products/ribbed-jersey-tube-cap-mauve-b94a47.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "One size — ribbed knit stretches to fit",
      "Ribbed cotton-blend jersey",
      "Closed tube with a single gathered seam at the centre back",
      "Textured surface stops the hijab sliding",
      "Machine wash cold on a gentle cycle. Cool iron if needed."
    ],
    "tags": [
      "top-selling"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "15",
    "slug": "tube-cap",
    "name": "Tube Cap",
    "subtitle": "Smooth and simple",
    "description": "A smooth jersey tube cap — the plain, comfortable base layer. Thin enough to disappear under a lightweight hijab and soft enough to wear all day.",
    "price": 12,
    "category": "Underscarves",
    "images": [
      "/products/tube-cap-chocolate-brown-d1ed69.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-15-chocolate-brown",
        "colorName": "Chocolate Brown",
        "hex": "#3c2a1e",
        "sku": "GG-TUBCAP-CHOBRO",
        "stock": 10,
        "images": [
          "/products/tube-cap-chocolate-brown-d1ed69.webp"
        ]
      },
      {
        "id": "v-15-black",
        "colorName": "Black",
        "hex": "#101010",
        "sku": "GG-TUBCAP-BLA",
        "stock": 10,
        "images": [
          "/products/tube-cap-black-7591bd.webp"
        ]
      },
      {
        "id": "v-15-beige",
        "colorName": "Beige",
        "hex": "#d8c1a4",
        "sku": "GG-TUBCAP-BEI",
        "stock": 10,
        "images": [
          "/products/tube-cap-beige-39ee1d.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "One size — jersey knit stretches to fit",
      "Smooth cotton-blend jersey",
      "Open-ended tube, twin-stitched hems top and bottom",
      "Thin enough to sit invisibly under light fabrics",
      "Machine wash cold on a gentle cycle. Cool iron if needed."
    ],
    "tags": [],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "16",
    "slug": "cocoa-ditsy-floral-scarf",
    "name": "Cocoa Ditsy Floral Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/cocoa-ditsy-floral-scarf-71e090.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "17",
    "slug": "indigo-marble-scarf",
    "name": "Indigo Marble Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/indigo-marble-scarf-4ea8fc.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "18",
    "slug": "plum-gold-marble-scarf",
    "name": "Plum Gold Marble Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/plum-gold-marble-scarf-7816a5.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "19",
    "slug": "taupe-watercolour-floral-scarf",
    "name": "Taupe Watercolour Floral Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/taupe-watercolour-floral-scarf-370c45.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "20",
    "slug": "fawn-dot-scarf",
    "name": "Fawn Dot Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/fawn-dot-scarf-2d1322.webp",
      "/products/fawn-dot-scarf-2-241d57.webp",
      "/products/fawn-dot-scarf-3-b9a45d.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "21",
    "slug": "olive-geometric-mosaic-scarf",
    "name": "Olive Geometric Mosaic Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/olive-geometric-mosaic-scarf-8b2796.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "22",
    "slug": "tan-brushstroke-stripe-scarf",
    "name": "Tan Brushstroke Stripe Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/tan-brushstroke-stripe-scarf-1308b2.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "23",
    "slug": "taupe-grey-marble-scarf",
    "name": "Taupe Grey Marble Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/taupe-grey-marble-scarf-e808e4.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "24",
    "slug": "cocoa-floral-bouquet-scarf",
    "name": "Cocoa Floral Bouquet Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/cocoa-floral-bouquet-scarf-f11be5.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "25",
    "slug": "olive-gold-swirl-marble-scarf",
    "name": "Olive Gold Swirl Marble Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/olive-gold-swirl-marble-scarf-b6ff15.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "26",
    "slug": "champagne-onyx-marble-scarf",
    "name": "Champagne Onyx Marble Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/champagne-onyx-marble-scarf-812af3.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "27",
    "slug": "charcoal-ink-floral-scarf",
    "name": "Charcoal Ink Floral Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/charcoal-ink-floral-scarf-f31310.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "28",
    "slug": "black-floral-scarf",
    "name": "Black Floral Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/black-floral-scarf-cbe050.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "29",
    "slug": "classic-leopard-scarf",
    "name": "Classic Leopard Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/classic-leopard-scarf-c6e11b.webp",
      "/products/classic-leopard-scarf-2-18d6e8.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "30",
    "slug": "ivory-floral-spray-scarf",
    "name": "Ivory Floral Spray Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/ivory-floral-spray-scarf-c45a1f.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "31",
    "slug": "ivory-espresso-marble-scarf",
    "name": "Ivory Espresso Marble Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/ivory-espresso-marble-scarf-3cf9ba.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "32",
    "slug": "indigo-floral-bouquet-scarf",
    "name": "Indigo Floral Bouquet Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/indigo-floral-bouquet-scarf-3745f3.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "33",
    "slug": "ivory-blush-floral-scarf",
    "name": "Ivory Blush Floral Printed Scarf",
    "subtitle": "Printed chiffon",
    "description": "A lightweight printed scarf in soft, fluid chiffon. The print runs across the full length, so it reads differently depending on how you fold it — draped long, wrapped, or knotted at the neck.",
    "price": 35,
    "category": "Scarves",
    "images": [
      "/products/ivory-blush-floral-scarf-30d4d5.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Lightweight chiffon with a soft, silky handle",
      "Semi-sheer — an underscarf is recommended for full coverage",
      "Hemmed edges",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [
      "new-arrivals"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "34",
    "slug": "slate-geometric-trellis",
    "name": "Slate Geometric Trellis",
    "subtitle": "Woven, not printed",
    "description": "A matte woven scarf with a trellis grid running through the body and a bold geometric key border at each end. Heavier and more opaque than our chiffon prints — this one sits like a light shawl.",
    "price": 39,
    "category": "Scarves",
    "images": [
      "/products/slate-geometric-trellis-4df787.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Approx. 180 × 70 cm",
      "Matte woven blend with a soft, slightly textured handle",
      "Opaque — no underscarf needed",
      "Woven trellis field with a geometric key border",
      "Hand wash cold or dry clean. Cool iron on the reverse."
    ],
    "tags": [],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "35",
    "slug": "hijab-pins",
    "name": "Hijab Pins",
    "subtitle": "Ball-head pins",
    "description": "Straight pins with rounded ball heads, boxed and ready to go in your bag. Fine enough not to mark a delicate weave, long enough to hold a double layer.",
    "price": 8,
    "category": "Hijab Accessories",
    "images": [
      "/products/hijab-pins-multicolour-040255.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-35-multicolour",
        "colorName": "Multicolour",
        "hex": "#dccdae",
        "sku": "GG-HIJPIN-MUL",
        "stock": 10,
        "images": [
          "/products/hijab-pins-multicolour-040255.webp"
        ]
      },
      {
        "id": "v-35-golden",
        "colorName": "Golden",
        "hex": "#c9a227",
        "sku": "GG-HIJPIN-GOL",
        "stock": 10,
        "images": [
          "/products/hijab-pins-golden-410af5.webp"
        ]
      },
      {
        "id": "v-35-black",
        "colorName": "Black",
        "hex": "#2c2c2e",
        "sku": "GG-HIJPIN-BLA",
        "stock": 10,
        "images": [
          "/products/hijab-pins-black-def43d.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Straight dressmaker-style pins, approx. 38 mm",
      "Steel shaft with a coloured ball head",
      "Supplied in a hinged storage box",
      "Pack quantity not printed on the box — confirm before ordering"
    ],
    "tags": [],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "36",
    "slug": "pearl-dressmaker-pins",
    "name": "Pearl Dressmaker Pins",
    "subtitle": "100 pieces",
    "description": "A hundred pearl-head pins in a resealable box. The larger pearl head is easier to grip and sits neatly against the fabric when pinned.",
    "price": 12,
    "category": "Hijab Accessories",
    "images": [
      "/products/pearl-dressmaker-pins-1f0351.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "100 pieces per box",
      "Steel shaft with a pearl-effect head",
      "Approx. 38 mm",
      "Resealable storage box"
    ],
    "tags": [],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "37",
    "slug": "hijab-magnets",
    "name": "Hijab Magnets",
    "subtitle": "No holes, no snags",
    "description": "Magnetic fasteners that hold your hijab closed without piercing the fabric — the answer for chiffon and silk, where a pin leaves a mark behind. Twelve domed caps in muted tones, cased and ready for your bag.",
    "price": 15,
    "category": "Hijab Accessories",
    "images": [
      "/products/hijab-magnets-smooth-matte-finish-set-12-tones-e5ef9c.webp"
    ],
    "video": null,
    "variants": [
      {
        "id": "v-37-smooth-matte-finish-set-12-tones",
        "colorName": "Smooth matte finish set (12 tones)",
        "hex": "#a8a29e",
        "sku": "GG-HIJMAG-SMOMAT",
        "stock": 10,
        "images": [
          "/products/hijab-magnets-smooth-matte-finish-set-12-tones-e5ef9c.webp"
        ]
      },
      {
        "id": "v-37-embossed-textured-finish-set-12-tones",
        "colorName": "Embossed textured finish set (12 tones)",
        "hex": "#8f8a80",
        "sku": "GG-HIJMAG-EMBTEX",
        "stock": 10,
        "images": [
          "/products/hijab-magnets-embossed-textured-finish-set-12-tones-e71cd4.webp"
        ]
      }
    ],
    "stock": 0,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Set of 12, one per compartment",
      "Holds without piercing — safe on chiffon, silk and georgette",
      "Matte domed caps in twelve muted tones",
      "Keep away from cards, watches and pacemakers"
    ],
    "tags": [
      "trending"
    ],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "38",
    "slug": "pastel-pearl-hijab-pins",
    "name": "Pastel Pearl Hijab Pins",
    "subtitle": "Assorted pastels",
    "description": "A small boxed set of pearl-head pins in soft pastels — blush, ivory, dove grey, lilac and black. The rounded pearl head is easy to grip and finishes neatly against the fabric.",
    "price": 14,
    "category": "Hijab Accessories",
    "images": [
      "/products/pastel-pearl-hijab-pins-7d00a6.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Pearl-effect heads on fine steel pins",
      "Assorted pastel shades",
      "Supplied in a clear hinged box that fits a handbag",
      "Pack quantity not printed on the box — confirm before ordering"
    ],
    "tags": [],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  },
  {
    "id": "39",
    "slug": "hijab-dress-tape",
    "name": "Hijab Dress Tape",
    "subtitle": "Double-sided",
    "description": "Double-sided fashion tape for the places a pin cannot reach — a neckline that gapes, a fold that will not sit. Skin-safe adhesive that peels away cleanly.",
    "price": 10,
    "category": "Hijab Accessories",
    "images": [
      "/products/hijab-dress-tape-de1c14.webp"
    ],
    "video": null,
    "variants": [],
    "stock": 10,
    "lowStockThreshold": 3,
    "sizes": [
      "One Size"
    ],
    "details": [
      "Double-sided fabric-to-skin tape",
      "Skin-safe adhesive, removes without residue",
      "Supplied in a resealable pouch",
      "Single use per strip — final sale for hygiene reasons"
    ],
    "tags": [],
    "status": "active",
    "createdAt": "2026-08-22T00:00:00.000Z",
    "updatedAt": "2026-08-22T00:00:00.000Z"
  }
];

export const PRODUCT_CATEGORIES = [
  "Hijabs",
  "Scarves",
  "Pashminas & Stoles",
  "Underscarves",
  "Hijab Accessories"
];

export const PRODUCT_TAGS = [
  { value: 'trending', label: 'Trending Now' },
  { value: 'new-arrivals', label: 'New Arrivals' },
  // Drives the home page hero carousel and the thumbnail strip beneath it.
  { value: 'top-selling', label: 'Top Selling' },
];
